repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.5
    hooks:
      - id: ruff-format
        types: [python]
        stages: [pre-commit]
        exclude: ^(build|dist)/
      - id: ruff
        args: [--fix]
        types: [python]
        stages: [pre-commit]
        exclude: ^(build|dist)/
