name: ci
on:
  push:
  pull_request:

jobs:
  lint:
    name: Ruff lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: python -m pip install -U pip ruff
      - run: ruff check src tests

  test-modern:
    name: Unit tests (3.8 / 3.10 / 3.12)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.10", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m pip install -U pip
      - name: Run tests (unittest)
        env:
          PYTHONPATH: src
        run: python -m unittest discover -s tests -v

  test-36:
    name: Unit tests (3.6 via container)
    runs-on: ubuntu-latest
    container: python:3.6-buster
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - run: python -V
      - run: python -m pip install -U pip
      - name: Run tests (unittest)
        env:
          PYTHONPATH: src
        run: python -m unittest discover -s tests -v
