name: ci
on:
  push:
  pull_request:

jobs:
  lint:
    name: Ruff lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install tools
        run: |
          python -m pip install -U pip
          pip install ruff
      - name: Run Ruff
        run: ruff check src tests

  test:
    name: Unit tests (matrix)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6.7", "3.8", "3.10", "3.12"]
    continue-on-error: ${{ matrix.python-version == '3.6' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install test deps
        run: |
          python -m pip install -U pip
      - name: Run tests (unittest)
        env:
          PYTHONPATH: src
        run: python -m unittest discover -s tests -v
